version: 2
jobs:

  # Branch/Merge Targets Configuration

  update_ucb_credentials:
    docker:
      - image: wormholegg/circleci-fastlane-android:latest
    steps:
      - checkout
      - run:
          name: Update Unity Cloud Build Credentials - Dev AdHoc
          no_output_timeout: 60m
          command: |
            scripts/credentials-4-ucb.bash \
              -a $UNITY_CLOUD_BUILD_API_KEY \
              -o tapthereinc \
              -cr 143487b3-d05e-4547-886e-bbfc1f35e071 \
              -de "Dev TestFlight" \
              -ce certs/distribution/TPF4K8R4MK.cer \
              -pk certs/distribution/TPF4K8R4MK.p12 \
              -pr profiles/appstore/AppStore_gg.wormhole.dev.ios.mobileprovision \
              -pp $TAPTHERE_PASSPHRASE
      - run:
          name: Update Unity Cloud Build Credentials - Dev AdHoc
          no_output_timeout: 60m
          command: |
            scripts/credentials-4-ucb.bash \
              -a $UNITY_CLOUD_BUILD_API_KEY \
              -o tapthereinc \
              -cr f82d9014-0cae-4d15-a06a-1940f5c120ae \
              -de "Dev AdHoc" \
              -ce certs/distribution/TPF4K8R4MK.cer \
              -pk certs/distribution/TPF4K8R4MK.p12 \
              -pr profiles/adhoc/AdHoc_gg.wormhole.dev.ios.mobileprovision \
              -pp $TAPTHERE_PASSPHRASE

workflows:
  version: 2
  "Update Unity Cloud Build Credentials":
    jobs:
      - update_ucb_credentials:
          filters:
            branches:
              only:
                - master
